name: backend-deploy-staging

on:
  push:
    tags:
      - stage**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: deploy
      uses: appleboy/ssh-action@v1.0.3
      env:
        ROBOFLOW_API_KEY: ${{ secrets.ROBOFLOW_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      with:
        host: ${{ secrets.STAGING_HOSTNAME }}
        username: "ubuntu"
        key: ${{ secrets.STAGING_SSH_KEY }}
        port: 22
        envs: GITHUB_SHA,ROBOFLOW_API_KEY,GEMINI_API_KEY
        script: |
          rm -r RecycleRight
          git clone https://github.com/RecycleRightCSE403/RecycleRight.git
          cd RecycleRight/
          git reset --hard $GITHUB_SHA
          cd backend/
          python3 -m venv venv
          source venv/bin/activate
          pip3 install -r requirements.txt
          echo ROBOFLOW_API_KEY=$ROBOFLOW_API_KEY > .env
          echo GEMINI_API_KEY=$GEMINI_API_KEY >> .env
          pip3 install gunicorn
          sudo systemctl daemon-reload
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
  
