name: flutter-test
on:
  push:
    paths:
      - 'frontend/recycleright/**'
      - '.github/workflows/flutter_test.yaml'
    workflow_dispatch:
jobs:
  drive:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/recycleright
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'
    - run: flutter pub get
    - run: flutter build apk
    - run: flutter test