name: flutter-tests
on: [push, workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/recycleright
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'
    - run: flutter pub get
    - run: flutter test
